### ISSUE TITLE
Nova 4 support

### ISSUE THREAD

**Issue by stepanenko3** [statikbe/laravel-nova-chained-translation-manager#12]

**Comment by FrittenKeeZ** [comment]
@nelumoraru I saw you working on Nova 4 support, using your repo to get it working, but the only thing causing issues is `canSee` for the tool.
```php
TranslationManager::make()->canSee(fn (Request $request) => $request->user()->is_super_admin)
```
I can't really figure out what's going wrong though, but maybe you have an idea?

**Comment by nelumoraru** [comment]
> @nelumoraru I saw you working on Nova 4 support, using your repo to get it working, but the only thing causing issues is `canSee` for the tool.
> 
> ```php
> 
> TranslationManager::make()->canSee(fn (Request $request) => $request->user()->is_super_admin)
> 
> ```
> 
> I can't really figure out what's going wrong though, but maybe you have an idea?

Not yet, trying to understand the whole package and figuring it out
