### ISSUE TITLE
Light mode not working properly on Nova 4

### ISSUE THREAD

**Issue by NoahNxT** [statikbe/laravel-nova-chained-translation-manager#15]
<img width="1545" alt="image" src="https://user-images.githubusercontent.com/58152024/195921576-a728fec1-348a-46f8-8d39-f364ea896a01.png">

**Comment by stijnelskens** [comment]
Hi @NoahNxT, this should be fixed in the latest release 3.0.1!

**Comment by NoahNxT** [comment]
Awesome, will test it tonight!
