### ISSUE TITLE
Language code 'es_419' overrides 'es' translations

### ISSUE THREAD

**Issue by 7ammer** [statikbe/laravel-nova-chained-translation-manager#18]
Hello :)

I'm having an issue where the language code for "Latin American Spanish" aka `es_419` overrides the "Spanish" translations `es` and nothing appears to get added to `es_419`. However, after reloading the page I can see that everything saves correctly.

My hunch is that the method `updateTranslations ` in the vue file is not accounting for language codes that start with the same two words and so updates incorrectly.

I'm using: v3.0.1

**Comment by 7ammer** [comment]
Replace line **293** of **Translation.vue** from:
`const [id, locale] = this.field.split("_");` 
to
`const [id, locale] = this.split(/_(.*)/s);`.

This should just split the first '_'.

**Comment by sten** [comment]
Thanks for your PR! It is released as v3.0.2
