### ISSUE TITLE
Changing translation from a third party package gives problems

### ISSUE THREAD

**Issue by kristofser** [statikbe/laravel-nova-chained-translation-manager#2]
Hello, 

When updating a translation for a third party package. The translator gives an exception on saving the new translation.
I believe the problem occurs when it needs to create new folders in the lang-custom folder.

I've included a screenshot to show you which error I got.
![image](https://user-images.githubusercontent.com/5928907/104577537-e50f5f00-5659-11eb-8917-99d1584ebb97.png)

**Comment by sten** [comment]
@kristofser I have tried with the library you use, and with others, but I am unable to reproduce this error. 
I removed the complete `lang-custom` directory and retried without success.

**Comment by kristofser** [comment]
@sten I updated the package to version 1.2.1 together with the [laravel chained translator package](https://github.com/statikbe/laravel-chained-translator) version 1.10

this fixed the problem. So thank you!
