### ISSUE TITLE
Not found resource. 

### ISSUE THREAD

**Issue by pblaravel** [statikbe/laravel-nova-chained-translation-manager#24]
<img width="2047" alt="image" src="https://user-images.githubusercontent.com/10829306/204137882-7f80974e-3f87-4e97-80f1-e2f5aa582f4e.png">

**Comment by pblaravel** [comment]
please help resolve this problem

**Comment by sten** [comment]
@pblaravel Can you provide us with more information?
From the screenshot, it looks like Laravel is not loading Nova. Can you check if /administrator works?

**Comment by pblaravel** [comment]
https://user-images.githubusercontent.com/10829306/204335150-b99d2a40-896f-49b0-8ccd-91d1e00ffc72.mov

**Comment by stijnelskens** [comment]
@pblaravel I did a clean install on new project and it works just fine here!

Can you provide your version of:
- Nova
- Laravel-nova-chained-translation-manager

Did you follow the right steps listed in the readme?

**Comment by pblaravel** [comment]
Nova : 4.19.3
Laravel-nova-chained-translation-manager: 3.0.4

**Comment by pblaravel** [comment]
Yes execute all steps from readme

**Comment by sten** [comment]
@pblaravel It is very hard to help you without seeing the code. We cannot replicate your situation.
Can you please provide the code in a git repo?

**Comment by sten** [comment]
I will close this, since it is not reproducable and no feedback is provided.
