### ISSUE TITLE
JSON localization support

### ISSUE THREAD

**Issue by ExsyDev** [statikbe/laravel-nova-chained-translation-manager#9]
Hello. We have a translation with default laravel function:

`{{ __('Locale') }}`

I can translate this string in en.json in folder `resources/lang/en.json`. How I can write json translations with this package?

**Comment by sten** [comment]
@ExsyDev This is not implemented yet and should be implemented in the laravel-chained-translator: see https://github.com/statikbe/laravel-chained-translator/issues/3

**Comment by Kobo-one** [comment]
Json support is now added in statikbe/laravel-chained-translator v.2.1.0.

**Comment by ExsyDev** [comment]
Json is not working. I have two files in lang directory (en.json, de.json) and translastion manager don't show it
